# -*- coding: utf-8 -*-
"""
loanwords_vi.py — Từ điển đọc THUẦN VIỆT VAY MƯỢN cho mọi từ tiếng Anh/Nhật
còn sót trong bản dịch (scan toàn bộ 652 chương 2026-08-19).

Cách đọc theo chuẩn LO:
  sex -> sét, loli -> lô li, hentai -> hen tai, anime -> a ni me,
  cosplay -> cót lay, NPC -> nờ pê xê, gank -> ganh

Nguyên tắc: từ nào cũng viết CÓ DẤU để Piper đọc đúng giọng tiếng Việt,
hết hiện tượng espeak-ng đọc kiểu IPA tiếng Anh -> glitch lặp âm.
Metadata header (txt/full/utf/ixdzs/https/chapter/word/for...) cũng map luôn
cho an toàn khi render trực tiếp file chương.
"""
import re

# ---------------------------------------------------------------
# Cụm từ đặc biệt (map trước — thay theo độ dài giảm dần)
# ---------------------------------------------------------------
PHRASE_MAP = {
    # câu tiếng Anh trong bài đọc (ch.079)
    "how are you, i'm fine, thank you, and you": "hao a du, ai am phai, thanh kiu, an du",
    "how are you": "hao a du",
    "i'm fine": "ai am phai",
    "thank you": "thanh kiu",
    "and you": "an du",
    # tên ghép
    "kung fu panda": "cung phu pan đa",
    "kung fu": "cung phu",
    "black beast": "blắc bít",
    "land rover": "len rô vơ",
    "sledge 7": "xlét bảy",
    "louis xvi": "lu i mười sáu",
    "mary sue": "mê ri su",
    "pure love bar": "piu rơ lóp ba",
    "full makeup": "phun mây cáp",
    "how are you": "hao a du",
    "cet-4": "xê ết bốn",
    "resident evil": "re zi đen i vin",
    "yagami iori": "da ga mi i ô ri",
    "q&a": "kiu en a",
    "tiktok": "tích tóc",
    "makka pakka, akka wakka, mikka makka mooo": "mác ca pác ca, ác ca oác ca, míc ca mác ca mô",
    "makka pakka, akka wakka, mikka makka": "mác ca pác ca, ác ca oác ca, míc ca mác ca",
    "makka pakka, appa yakka, ikka akka ooo": "mác ca pác ca, áp pa dác ca, íc ca ác ca ô",
}

# ---------------------------------------------------------------
# Từ đơn (map sau — thay theo độ dài giảm dần)
# ---------------------------------------------------------------
MAP = {
    # --- theo chuẩn LO ---
    "sex": "sét",
    "loli": "lô li",
    "hentai": "hen tai",
    "anime": "a ni me",
    "cosplay": "cót lay",
    "npc": "nờ pê xê",
    "gank": "ganh",

    # --- đời sống / vật dụng ---
    "taxi": "tắc xi",
    "tiktok": "tích tóc",
    "call": "co",
    "video": "vi đê ô",
    "sofa": "sô pha",
    "bar": "ba",
    "game": "gêm",
    "tv": "ti vi",
    "camera": "ca mê ra",
    "yoga": "dô ga",
    "ok": "ô kê",
    "vali": "va li",
    "vest": "vét",
    "id": "ai đi",
    "ipad": "ai pát",
    "ipa": "ai pát",
    "sticker": "xích ke",
    "love": "lóp",
    "pure": "piu rơ",
    "jean": "gin",
    "jeans": "gin",
    "poster": "pót tơ",
    "salad": "sa lát",
    "gara": "ga ra",
    "cocktail": "cốc tai",
    "diy": "đi ai",
    "wechat": "vây chát",
    "app": "áp",
    "meme": "mim",
    "coca": "cô ca",
    "short": "sọt",
    "cafe": "cà phê",
    "hamster": "ham xơ",
    "centimet": "xen ti mét",
    "milimet": "mi li mét",
    "tatami": "ta ta mi",
    "buffet": "búp phê",
    "sledge": "xlét",
    "qr": "ki u a",
    "kfc": "ka ép xê",
    "laptop": "láp tóp",
    "bikini": "bi ki ni",
    "streamer": "xờ rim mơ",
    "kung": "cung",
    "buff": "báp",
    "combo": "côm bô",
    "fan": "phan",
    "robot": "rô bốt",
    "lolita": "lô li ta",
    "virus": "vi rút",
    "wink": "uyn",
    "flash": "phờ lát",
    "sb": "sờ bờ",
    "joker": "giô kơ",
    "boss": "bốt",
    "collagen": "cô la gen",
    "murphy": "mơ phy",
    "hr": "hát rờ",
    "emoji": "ê mô zi",
    "solo": "xô lô",
    "louis": "lu i",
    "yagami": "da ga mi",
    "iori": "i ô ri",
    "nude": "nút",
    "fbi": "ép bi ai",
    "oxy": "ô xi",
    "logo": "lô gô",
    "doujinshi": "đô jin si",
    "bug": "bác",
    "avatar": "a va ta",
    "cd": "xi đê",
    "blouse": "blau",
    "check": "chéc",
    "group": "gúp",
    "coser": "cô sơ",
    "gym": "gim",
    "website": "uép sai",
    "fullscreen": "phun xờ crin",
    "npc": "nờ pê xê",
    "shabi": "sa bi",
    "panda": "pan đa",
    "danmei": "đan mây",
    "chip": "chíp",
    "lcd": "lờ xê đê",
    "bye": "bai",
    "mary": "mê ri",
    "internet": "in tơ nét",
    "gen": "gien",
    "gene": "giên",
    "carbon": "các bon",
    "neon": "nê on",
    "tsundere": "xun đê rê",
    "micro": "mai crô",
    "nilon": "ni lông",
    "hawaii": "ha oai",
    "radar": "ra đa",
    "sandwich": "xan uýt",
    "show": "sâu",
    "play": "pây",
    "led": "lét",
    "ssr": "ét ét a",
    "parkinson": "pa kin sơn",
    "lolicon": "lô li con",
    "protein": "prô tê in",
    "cello": "xê lô",
    "feynman": "phây nơ man",
    "balo": "ba lô",
    "hotboy": "hót bồi",
    "crawl": "crôn",
    "canxi": "can xi",
    "chapter": "cháp tơ",
    "hoodie": "hu đi",
    "squat": "xoát",
    "you": "du",
    "selfie": "xen phi",
    "ip": "ai pi",
    "rank": "răng",
    "ship": "síp",
    "pikachu": "pi ka chu",
    "word": "uớt",
    "icu": "i xi u",
    "domino": "đô mi nô",
    "gala": "ga la",
    "massage": "ma xa",
    "web": "uép",
    "lane": "lên",
    "auto": "ô tô",
    "chess": "chét",
    "hormone": "hóc môn",
    "menu": "mê nu",
    "flan": "phờ lăng",
    "thomas": "tô mat",
    "amstrong": "am xoong",
    "slide": "xlai",
    "socola": "sô cô la",
    "limousine": "li mô zin",
    "sadako": "sa đa cô",
    "copy": "cô pi",
    "loopy": "lu pi",
    "secondhand": "sơ cơn hẹn",
    "size": "sai",
    "sedan": "sê đan",
    "guitar": "ghi ta",
    "lincoln": "lin côn",
    "cet": "xê ết",
    "sms": "ét mờ ét",
    "cpu": "xi pi u",
    "pandora": "pan đô ra",
    "pro": "prô",
    "gram": "gam",
    "pk": "pi ka",
    "acc": "ác",
    "sexy": "xéc si",
    "taobao": "tao bao",
    "michelin": "mi sơ linh",
    "hack": "hắc",
    "farm": "phăm",
    "boxing": "bốc xinh",
    "cg": "xi gi",
    "online": "on lain",
    "aphelios": "a phê li ôt",
    "lag": "lắc",
    "girl": "gớt",
    "ptsd": "pi ti ét đê",
    "value": "va lu",
    "smith": "xmít",
    "bill": "bin",
    "gates": "gết",
    "woa": "u oa",
    "dance": "đan xơ",
    "mini": "mi ni",
    "doraemon": "đô ra ê môn",
    "bartender": "ba ten đơ",
    "dopamine": "đô pa min",
    "disco": "đích cô",
    "makeup": "mây cáp",
    "eyeliner": "ai lai nơ",
    "orange": "o rên",
    "olympic": "ô lim pích",
    "catwalk": "ké tuốc",
    "teppanyaki": "tép pan da ki",
    "lol": "lô",
    "boston": "bốt tơn",
    "caro": "ca rô",
    "club": "câu lạp",
    "gatling": "gát linh",
    "vitamin": "vi ta min",
    "abcdefg": "a bê xê đê e ép gờ",
    "uv": "u vê",
    "https": "hát típ",
    "compa": "com pa",
    "vip": "víp",
    "nokia": "nô ki a",
    "bolt": "bô lơ",
    "bzzz": "bờ zờ zờ",
    "tsinghua": "thanh hoa",
    "karaoke": "ca ra ô kê",
    "tieba": "thi ba",
    "saiya": "sai da",
    "ultraman": "un tra man",
    "pass": "pát",
    "are": "a",
    "fine": "phai",
    "thank": "thanh",
    "and": "an",
    "album": "an bum",
    "bungee": "ban gi",
    "black": "blắc",
    "beast": "bít",
    "flagship": "phờ lác síp",
    "rnm": "a en em",
    "io": "ai ô",
    "land": "len",
    "rover": "rô vơ",
    "sim": "xim",
    "carton": "cát tông",
    "view": "viu",
    "netizen": "ne ti zen",
    "for": "pho",
    "tiramisu": "ti ra mi su",
    "pixel": "pích xen",
    "matcha": "mát cha",
    "mcdonald": "móc đô nôn",
    "maillard": "ma y la",
    "caramel": "ca ra men",
    "resident": "re zi đen",
    "evil": "i vin",
    "vani": "va ni",
    "latte": "la tê",
    "bluetooth": "blu tút",
    "hellokitty": "he lô ki ti",
    "seal": "xiu",
    "mic": "míc",
    "wtf": "uô tê ép",
    "byd": "bi uai đi",
    "wagyu": "oa giu",
    "lais": "lây",
    "tank": "tăng",
    "baron": "ba rôn",
    "mainstream": "mây sờ trim",
    "formaldehyde": "pho môn đê hít",
    "atm": "a tê em",
    "trend": "trét",
    "eq": "ê cu",
    "match": "mét",
    "logic": "lô gíc",
    "ntr": "nờ tê rờ",
    "tv": "ti vi",
    "ad": "a đê",
    "kung": "cung",
    "fu": "phu",
    "support": "xúp pọt",
    "kennen": "ken nen",
    "manga": "man ga",
    "goblin": "gốp lin",
    "sukiyaki": "xu ki da ki",
    "cos": "cót",
    "flash": "phờ lát",
    "gank": "ganh",
    "bbq": "bi bi cu",
    "qaq": "ki u a",
    "koi": "cô i",
    "kaki": "ca ki",
    "xvi": "mười sáu",
    "vx": "vê xờ",
    "nb": "niu bi",
    "sh": "sờ hát",
    "cen": "xen",
    "iq": "i cu",
    "cmnd": "xê em en đê",
    "mm": "mi li mét",
    "km": "ki lô mét",
    "fans": "phan",
    "txt": "tê xê tê",
    "full": "phun",
    "utf": "u tê ép",
    "ixdzs": "ích xì đê dét xì",
    "fanqie": "phan thiết",
    "fanqienovel": "phan thiết nô ven",
    "reader": "rê đơ",
    "info": "in phô",
    "truelove": "tru lóp",
    "ii": "i i",
}

# Từ dài hơn -> thay trước (tránh "flash" nuốt "flashlight", "bar" nuốt "baron"...)
_ORDERED = sorted(PHRASE_MAP.items(), key=lambda kv: -len(kv[0]))
_ORDERED_WORDS = sorted(MAP.items(), key=lambda kv: -len(kv[0]))


def _load_dynamic():
    """Kho từ động (loanwords_dynamic.json) — tự học từ mới khi render TTS.
    Trả về dict rỗng nếu chưa có file hoặc lỗi đọc."""
    try:
        import json
        from pathlib import Path
        f = Path(__file__).parent / "loanwords_dynamic.json"
        if not f.exists():
            return {}
        return json.loads(f.read_text(encoding="utf-8"))
    except Exception:
        return {}


def apply_loanwords(text: str) -> str:
    """Thay mọi từ Anh/Nhật bằng cách đọc thuần Việt (có dấu). An toàn: chỉ
    khớp cả từ đứng độc lập (có ranh giới từ Latin), không đụng từ tiếng Việt.
    Chỉ dùng kho từ động (loanwords_dynamic.json) — kho cứng đã merge vào."""
    # cụm từ trước (PHRASE_MAP vẫn giữ nguyên)
    for src, dst in _ORDERED:
        text = re.sub(rf"(?<![A-Za-z]){re.escape(src)}(?![A-Za-z])", dst, text, flags=re.IGNORECASE)
    # từ đơn: chỉ dùng kho động
    dynamic = _load_dynamic()
    ordered = sorted(dynamic.items(), key=lambda kv: -len(kv[0]))
    for src, dst in ordered:
        text = re.sub(rf"(?<![A-Za-z]){re.escape(src)}(?![A-Za-z])", dst, text, flags=re.IGNORECASE)
    return text


if __name__ == "__main__":
    tests = [
        "Lâm Dư cắm cúi chơi game, đám NPC heo này cứ gây phiền phức.",
        "Cô ấy cosplay anime, mặc bikini đi hội chợ cos.",
        "Đi solo với ai à? Đi ăn buffet sukiyaki ở quán bar.",
        "How are you, I'm fine, Thank you, and you",
        "Makka Pakka, Akka Wakka, Mikka Makka Mooo.",
        "Cốt truyện sex của nữ chính số hai, giờ còn để AD.",
        "Ngồi trên sofa xem video, gọi cocktail, thấy ID run lên.",
    ]
    for t in tests:
        print("IN :", t)
        print("OUT:", apply_loanwords(t))
        print()